name: MainCIPipeline

on:
  push:
    branches: ["main"]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet sdk
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Generate env file
        run: |
          chmod +x scripts/generate-env-file.sh
          ./scripts/generate-env-file.sh "${{ secrets.DB_CONNECTION_STRING }}" "${{ secrets.DB_PASSWORD }}" "${{ secrets.DB_NAME }}" "${{ secrets.JWT_KEY }}" "${{ vars.JWT_AUDIENCE }}" "${{ vars.JWT_ISSUER }}" "${{ secrets.AUTH_APIKEY }}" 
        working-directory: ./
      
      - name: Build solution
        run: docker-compose up --exit-code-from builder builder
        
      - name: Run unit tests
        run: docker-compose up --exit-code-from unit-tests unit-tests

      - name: Run integration tests
        run: docker-compose up --exit-code-from integration-tests integration-tests
